# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem 'cocoapods', '1.11.2'
gem 'danger-gitlab', '8.0.0'
gem 'danger-junit', '1.0.2'
gem 'danger-swiftlint', '0.29.4'
gem 'dotenv', '2.7.6'
gem 'fastlane', '2.204.2'
gem 'jira-ruby', '2.2.0'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
